class ApiConstant {
  //https://BeeDegree.my-alphatech.com/api/Library/GetListTopics?PageNum=1

  static const baseUrl = 'https://BeeDegree.my-alphatech.com/api/Scenario/';
  static const getGetCoinsEndPoint = 'GetCoins';
  static const String token =
      'Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwidHlwIjoiSldUIiwiY3R5IjoiSldUIn0..-31OTPXnfbsjU51RWqRL_g.zEKcO-ppx_JbzNjKtyteemnV_KKepZMisoaI2rlZW9NVLX7ZLXwyjuAO4Lnd2yqAHQAAKr_JAdAI-qCJ6my-ao6nlsfn-788VW0J19NTrfklTPncpRCV_Kf6ZNYHeaku6UVQkfJRCUTnDIQnq2K8RBpgG2Zk6DH05CWecfm7OWExIfE0JVIr8X5NCiOCq5tF7UzcpcjYxP1iyTmr4-0xSsBlb2IQDS9GzjBZRcUHsnejLOe17h4LalKlu8rn3Em1KxjDpRVfcFsmKSOT6ZYhKam-hTxcUWfj5mFrxzLZwPmDD74sMj_pIAVuIi32Gcilcby_wYJfk88ZtSJMzJmIWIEO2LnmWZfzRgKNwBLs2zAHhND5RkBqK3sjg5nxwaJKOBfajXMo0bwRoZCg5eCg6eF-z7NZ3ev6snIioFCkhCQRp5J66RQRGgJJOXiOJx1gf4xGwMjlKLiZPOHN0HsWue9VnyZk0ARCe2DsEhVVo5Q.jp-tzqzJ25BOj7WPwXmbkoTal6pXA-VPGGqU_M9uZ5g';
}
